# Generated by Django 4.2.6 on 2023-10-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('machine', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('total_memory', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internet_connected', models.BooleanField(default=False)),
                ('installed_apps', models.IntegerField(default=0)),
                ('running_processes', models.IntegerField(default=0)),
            ],
        ),
    ]
